version: '3.8'
services: 
    web:
        image: letsdocker:1.0
        build: .
        command: "node index.js"
        ports:
            - "5000:5000"
        depends_on:
            - "mongo"
    mongo:
        image: "mongo"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${DBNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${PASS}
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
volumes: 
    mongo-data:
        driver: local